# Generated by Django 5.0.6 on 2024-05-25 09:58

import server.models
import server.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='icon',
        ),
        migrations.AddField(
            model_name='server',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.server_banner_upload_path, validators=[server.validator.validator_image_file_exstension]),
        ),
        migrations.AddField(
            model_name='server',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.server_icon_upload_path, validators=[server.validator.validator_icon_image_size, server.validator.validator_image_file_exstension]),
        ),
    ]
